name: Secret scan

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  gitleaks-scan:
    name: Gitleaks scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Gitleaks
        uses: zricethezav/gitleaks-action@v1.2.2
        with:
          args: --verbose --redact
